name: flutter_dart_file_generator
description: Generate your dart file with ease.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  cli_dialog: ^0.5.0
  recase: ^4.0.0

dev_dependencies:
  lints: ^1.0.0
